FROM analylit-base:latest

# Copie du code spécifique web
COPY . .
COPY entrypoint.sh /home/appuser/app/entrypoint.sh

USER root
RUN chmod +x /home/appuser/app/entrypoint.sh
USER appuser

EXPOSE 5000
ENTRYPOINT ["./entrypoint.sh"]