# Utilise l'image de base qui contient déjà toutes les dépendances Python
FROM analylit-base-cpu:latest

# Définit le répertoire de travail et l'utilisateur
WORKDIR /home/appuser/app
USER appuser

# Copier TOUT le code source du projet (le contexte est la racine '.')
COPY --chown=appuser:appuser . .

# Installer notre projet comme un package Python pour des imports stables
RUN pip install -e .

# La commande par défaut (sera surchargée par docker-compose)
CMD ["echo", "Worker image ready."]
