# Utilise l'image de base où tout est déjà installé
FROM analylit-base:latest

# Le WORKDIR est déjà défini dans la base, mais le répéter est une bonne pratique
WORKDIR /home/appuser/app

# COPIER LE CODE SOURCE DANS LE WORKDIR DÉJÀ EXISTANT
COPY --chown=appuser:appuser . .