// web/js/constants.js

// Sélecteurs DOM centralisés
export const SELECTORS = {
    sections: '.section',
    navButtons: '.app-nav__button',
    connectionStatus: '[data-connection-status]',
    projectsList: '#projectsList',
    createProjectBtn: '#createProjectBtn',
    projectDetail: '#projectDetail',
    projectDetailContent: '#projectDetailContent',
    projectPlaceholder: '#projectPlaceholder',
    resultsContainer: '#resultsContainer',
    validationContainer: '#validationContainer',
    analysisContainer: '#analysisContainer',
    importContainer: '#importContainer',
    chatContainer: '#chatContainer',
    settingsContainer: '#settingsContainer',
    robContainer: '#robContainer',
    modalsContainer: '#modalsContainer',
    loadingOverlay: '#loadingOverlay',
    toastContainer: '#toastContainer',
    reportingContainer: '#reportingContainer',
    tasksContainer: '#tasksContainer',
    newProjectForm: '#newProjectForm',
    gridsContainer: '#gridsContainer',
    searchContainer: '#searchContainer',
    selectedArticles: '.article-checkbox:checked',
    analysisProgress: '#analysis-progress',
    analysisResults: '#analysis-results',
    settingsForm: '#profile-edit-form',
    ollamaModels: '#ollama-models-select',
    sidebar: '#sidebar',
    mainContent: '#main-content',
    loadingSpinner: '#loading-spinner',
    gridFieldDesc: '.grid-field-desc',
    zoteroFileInput: '#zoteroFileInput',
    bulkPDFInput: '#bulkPDFInput',
    pmidList: '#pmid-list',
    zoteroUserId: '#zoteroUserId',
    zoteroApiKey: '#zoteroApiKey',
    chatInput: '#chatInput',
    chatMessages: '#chatMessages'
};

// URLs API centralisées
export const API_ENDPOINTS = {
    // Projects
    projects: '/projects',
    projectById: (id) => `/projects/${id}`,
    projectExport: (id) => `/projects/${id}/export`,
    projectPrismaChecklist: (id) => `/projects/${id}/prisma-checklist`,
    projectRunAnalysis: (id) => `/projects/${id}/run-analysis`,
    projectExportAnalyses: (id) => `/projects/${id}/export/analyses`,
    projectExportThesis: (id) => `/projects/${id}/export/thesis`,
    
    // Grids
    grids: (projectId) => `/projects/${projectId}/grids`,
    gridById: (projectId, gridId) => `/projects/${projectId}/grids/${gridId}`,
    gridImport: (projectId) => `/projects/${projectId}/grids/import`,

    // Articles
    articlesBatchDelete: '/articles/batch-delete',
    projectSearchResults: (id) => `/projects/${id}/search-results`,
    
    // Analyses
    projectExtractions: (id) => `/projects/${id}/extractions`,
    projectRun: (id) => `/projects/${id}/run`,
    
    // Settings
    analysisProfiles: '/analysis-profiles',
    analysisProfileById: (id) => `/analysis-profiles/${id}`,
    prompts: '/prompts',
    promptById: (id) => `/prompts/${id}`,
    
    // Queues
    queuesInfo: '/queues/info',
    queuesClear: '/queues/clear',

    // Databases
    databases: '/databases',

    // Tasks
    taskCancel: (id) => `/tasks/${id}/cancel`,
    taskRetry: (id) => `/tasks/${id}/retry`,
    tasksStatus: '/tasks/status',

    // Search
    search: '/search',

    // Ollama
    ollamaPull: '/ollama/pull',
    ollamaModels: '/ollama/models',

    // Import
    projectBulkPdfDownload: (id) => `/projects/${id}/bulk-pdf-download`,
    projectIndexPdfs: (id) => `/projects/${id}/index-pdfs`,
    projectImportZotero: (id) => `/projects/${id}/import-zotero`,
    projectAddManualArticles: (id) => `/projects/${id}/add-manual-articles`,
    settingsZotero: '/settings/zotero',
    projectUploadPdfsBulk: (id) => `/projects/${id}/upload-pdfs-bulk`,

    // Chat
    projectChatHistory: (id) => `/projects/${id}/chat/history`,
    projectChat: (id) => `/projects/${id}/chat`,
    projectScreeningDecisions: (id) => `/projects/${id}/screening-decisions`,
};,

    // Validation
    projectExtractionDecision: (projectId, extractionId) => `/projects/${projectId}/extractions/${extractionId}/decision`,
    projectCalculateKappa: (projectId) => `/projects/${projectId}/calculate-kappa`,

    // Reporting
    projectBibliography: (id, style) => `/projects/${id}/reports/bibliography?style=${style}`,
    projectSummaryTable: (id) => `/projects/${id}/reports/summary-table`,
    projectExportSummaryTable: (id) => `/projects/${id}/reports/summary-table/export/excel`,

    // RoB
    projectRob: (projectId, articleId) => `/projects/${projectId}/risk-of-bias/${articleId}`,
    projectRunRobAnalysis: (projectId) => `/projects/${projectId}/run-rob-analysis`,
};

// Messages d'état
export const MESSAGES = {
    loading: 'Chargement en cours...', 
    // App
    appStart: '🚀 Démarrage de AnalyLit V4.1 Frontend (Version améliorée)...',
    missingDOMElement: 'Éléments DOM critiques manquants:',
    errorUI: "Erreur : éléments d'interface manquants",
    appInitialized: (time) => `✅ Application initialisée en ${time}ms`,
    initError: "❌ Erreur d'initialisation:",
    loadError: "Impossible de charger l'application. Rechargez la page.",
    initialDataLoaded: (time) => `📊 Données initiales chargées en ${time}ms`,
    initialDataError: 'Erreur chargement initial:',
    appStateLog: 'État de l'application:',
    debugInterface: '🎯 Interface de debug disponible: window.AnalyLit',
    // Projets
    projectCreated: 'Projet créé avec succès',
    projectDeleted: 'Projet supprimé',
    projectNameRequired: 'Le nom du projet est requis.',
    creatingProject: 'Création du projet...', 
    deletingProject: 'Suppression du projet...', 
    projectIdMissingForExport: "ID du projet manquant pour l'exportation.",
    projectExportStarted: "L'exportation du projet a commencé...",
    confirmDeleteProjectTitle: 'Confirmer la suppression',
    confirmDeleteProjectBody: (name) => `Êtes-vous sûr de vouloir supprimer le projet "<strong>${name}</strong>" ?`,
    // Articles
    loadingResults: 'Chargement des résultats...', 
    noProjectSelected: 'Aucun projet sélectionné',
    selectProjectToViewResults: 'Sélectionnez un projet pour voir les résultats de recherche.',
    errorLoadingResults: 'Erreur de chargement des résultats.',
    articleNotFound: 'Article introuvable',
    articleDetailsTitle: "Détails de l'article",
    noArticleSelected: 'Aucun article sélectionné',
    confirmDeleteArticles: (count) => `Supprimer ${count} article(s) sélectionné(s) ?`,
    deleteStarted: (jobId) => `Suppression lancée (Job ID: ${jobId})`,
    batchProcessModalTitle: 'Lancer le Screening par Lot',
    screeningStarted: (count) => `Lancement du screening pour ${count} article(s)...`,
    screeningTaskStarted: 'Tâche de screening lancée en arrière-plan.',
    noArticleToExtract: "Aucun article n'a été marqué comme 'Inclus' pour l'extraction.",
    fullExtractionModalTitle: 'Extraction Complète',
    noGridSelectedForExtraction: "Veuillez sélectionner une grille d'extraction",
    extractionStarted: (count) => `Lancement de l'extraction pour ${count} article(s)...`,
    extractionTaskStarted: 'Extraction complète lancée en arrière-plan.',
    noProjects: 'Aucun projet trouvé. Créez-en un pour commencer !',
    noArticles: 'Aucun article dans ce projet.',
    noArticlesFoundTitle: 'Aucun article trouvé',
    noArticlesFoundText: 'Lancez une recherche pour commencer à collecter des articles.',
    // Analyses
    analysisStarted: 'Analyse lancée avec succès',
    selectProjectToViewAnalyses: 'Sélectionnez un projet pour voir les analyses.',
    errorLoadingAnalyses: 'Erreur lors du chargement des analyses',
    savingPrisma: 'Sauvegarde PRISMA...', 
    prismaSaved: 'Progression PRISMA sauvegardée.',
    prismaExportNotImplemented: 'Export PRISMA non implémenté.',
    atnAnalysisStarted: "Lancement de l'analyse ATN...",
    atnAnalysisJobStarted: (jobId) => `Analyse ATN lancée (Job ID: ${jobId})`,
    selectProjectFirst: 'Veuillez d'abord sélectionner un projet.',
    startingAnalysis: (type) => `Lancement de la génération pour ${type}...`,
    unknownAnalysisType: "Type d'analyse inconnu.",
    analysisJobStarted: (type, jobId) => `La génération pour ${type} a été lancée (Job: ${jobId}).`,
    analysisStartedSimple: (type) => `La génération pour ${type} a été lancée.`, 
    errorStartingAnalysis: "Erreur lors du lancement de l'analyse",
    advancedAnalysisModalTitle: 'Lancer une Analyse Avancée',
    startingMetaAnalysis: 'Lancement de la méta-analyse...', 
    metaAnalysisStarted: 'Méta-analyse lancée avec succès.',
    startingDescriptiveStats: 'Calcul des statistiques descriptives...', 
    descriptiveStatsStarted: 'Calcul des statistiques lancé.',
    selectProjectToExportAnalyses: 'Veuillez sélectionner un projet pour exporter les analyses.',
    preparingExport: "Préparation de l'exportation...",
    analysisExportStarted: "L'exportation des analyses a commencé.",
    errorExportingAnalyses: "Erreur d'exportation",
    noDataForGraph: 'Aucune donnée pour le graphe. Lancez l'analyse pour le générer.',
    graphStats: (nodes, edges) => `${nodes} noeuds et ${edges} relations.`, 
    // Settings
    errorLoadingPrompts: 'Erreur chargement prompts',
    loadingSettingsData: 'Chargement des données de configuration...', 
    settingsDataNotReady: "Les données des paramètres ne sont pas prêtes, le rendu est annulé.",
    noAnalysisProfileFound: 'Aucun profil d'analyse trouvé.',
    refreshingQueuesStatus: "Rafraîchissement du statut des files...",
    noPromptTemplateFound: 'Aucun modèle de prompt trouvé.',
    noOllamaModelFound: 'Aucun modèle Ollama trouvé',
    aceNotLoaded: "La bibliothèque Ace n'a pas pu être chargée.",
    aceRetry: "Ace non chargé. Nouvel essai dans 100ms.",
    aceInitError: (type) => `Impossible d'initialiser l'éditeur Ace pour ${type}.`,
    cannotDeleteDefaultProfile: "Impossible de supprimer le profil par défaut.",
    deleteThisProfile: "Supprimer ce profil",
    templateApplied: (name, type) => `Modèle '${name}' appliqué aux éditeurs '${type}'.`,
    cannotApplyTemplate: `Impossible de déterminer à quel éditeur ce modèle s'applique. Veuillez sélectionner un onglet.`, 
    saving: 'Sauvegarde...', 
    profileSaved: (name) => `Profil '${name}' sauvegardé.`, 
    errorSavingProfile: "Erreur lors de la sauvegarde du profil:",
    cannotDeleteProfile: "Impossible de supprimer ce profil (défaut ou non sélectionné).",
    confirmProfileDeleteTitle: 'Confirmer la suppression',
    confirmProfileDeleteBody: (name) => `Êtes-vous sûr de vouloir supprimer définitivement le profil "${name}" ?`,
    deleteButton: 'Supprimer',
    profileDeleted: (name) => `Profil "${name}" supprimé.`, 
    errorDeletingProfile: "Erreur lors de la suppression du profil:",
    clearQueueTitle: 'Vider la file d\'attente',
    confirmClearQueueBody: (name) => `Êtes-vous sûr de vouloir vider la file "${name}" ? Toutes les tâches en attente seront perdues.`, 
    clearButton: 'Vider',
    queueCleared: (name) => `La file "${name}" a été vidée.`, 
    promptSaved: 'Modèle de prompt sauvegardé.',
    selectNotFound: "L'élément select 'available-models-select' est introuvable.",
    modelListNotFound: "Erreur : Impossible de trouver la liste des modèles.",
    modelDownloaded: (name) => `Modèle ${name} téléchargé avec succès`,
    unknownError: 'Erreur inconnue',
    downloadError: 'Erreur téléchargement',
    downloadingModel: (name) => `Téléchargement de ${name}...`,
    noDescription: 'Pas de description.',
    chooseModel: '-- Choisir un modèle --',
    noWorkerDetected: 'Aucun worker actif détecté.',
    tasksNotProcessed: 'Les tâches ne seront pas traitées.',
    profileNotFound: (id) => `Profil non trouvé: ${id}`,
    // Grids
    errorLoadingGrids: 'Erreur lors du chargement des grilles.',
    selectProjectToViewGrids: 'Sélectionnez un projet pour voir ses grilles.',
    noCustomGrids: 'Aucune grille personnalisée.',
    confirmDeleteGrid: 'Supprimer cette grille ?',
    gridDeleted: 'Grille supprimée.',
    editGridTitle: 'Modifier la Grille',
    createGridTitle: 'Créer une Nouvelle Grille',
    invalidJsonFile: 'Veuillez sélectionner un fichier .json valide.',
    gridImported: 'Grille importée avec succès.',
    gridNameAndFieldRequired: 'Le nom de la grille et au moins un champ sont requis.',
    gridSaved: (isUpdate) => `Grille ${isUpdate ? 'mise à jour' : 'créée'} avec succès.`, 
    errorSavingGrid: 'Erreur lors de la sauvegarde de la grille',
    fieldNamePlaceholder: 'Nom du champ',
    fieldDescriptionPlaceholder: 'Description (optionnel)',
    // Core
    taskCancelRequestSent: "Demande d'annulation de la tâche envoyée.",
    taskCancelError: "Erreur lors de l'annulation",
    taskRetrySuccess: (id) => `Tâche ${id} relancée.`, 
    taskRetryError: "Erreur lors de la relance",
    socketUnavailable: 'Client Socket.IO indisponible.',
    websocketConnected: '✅ WebSocket connecté',
    websocketDisconnected: '🔌 WebSocket déconnecté.',
    notificationReceived: '🔔 Notification reçue:',
    analysisComplete: (type) => `Analyse "${type}" terminée.`, 
    refreshingAnalyses: 'Rafraîchissement de la section analyses...', 
    searchComplete: (count) => `Recherche terminée: ${count} articles trouvés.`, 
    refreshingResults: 'Rafraîchissement de la section résultats...', 
    websocketError: 'Erreur WebSocket:',
    firstRender: (section) => `First render for section: ${section}`,
    // Search
    selectProjectForSearch: 'Veuillez sélectionner un projet pour commencer une recherche.',
    expertQueryRequired: 'Veuillez saisir au moins une requête en mode expert.',
    queryRequired: 'Veuillez saisir une requête de recherche.',
    searching: 'Recherche en cours...', 
    searchStarted: 'Recherche lancée en arrière-plan. Les résultats apparaîtront progressivement.',
    selectProjectToSearch: 'Veuillez sélectionner un projet pour lancer une recherche.',
    newSearchModalTitle: 'Nouvelle Recherche',
    // Screening
    loadingScreening: 'Chargement du screening...', 
    errorLoadingScreening: 'Erreur de chargement du screening',
    selectProjectForScreening: 'Sélectionnez un projet pour commencer le screening.',
    noArticlesToScreen: 'Aucun article à screener. Lancez un traitement par lot.',
    // Reporting
    selectProjectForReporting: 'Veuillez sélectionner un projet pour accéder aux rapports.',
    generatingBibliography: 'Génération de la bibliographie...', 
    bibliographyNotImplemented: 'Génération de la bibliographie non implémentée.',
    errorGeneratingBibliography: 'Erreur lors de la génération de la bibliographie.',
    generatingSummaryTable: 'Génération du tableau de synthèse...', 
    summaryTableNotImplemented: 'Génération du tableau de synthèse non implémentée.',
    errorGeneratingSummaryTable: 'Erreur lors de la génération du tableau de synthèse.',
    exportingExcel: 'Exportation du tableau en Excel...', 
    exportExcelNotImplemented: 'Exportation du tableau non implémentée.',
    errorExportingExcel: 'Erreur lors de l\'exportation du tableau en Excel.',
    loadingPrisma: 'Chargement de la checklist PRISMA-ScR...', 
    prismaLoaded: 'Checklist PRISMA-ScR chargée.',
    errorLoadingPrisma: 'Erreur lors du chargement de la checklist PRISMA-ScR.',
    prismaUnavailable: 'Checklist PRISMA-ScR non disponible.',
    savingPrismaChecklist: 'Sauvegarde de la checklist PRISMA-ScR...', 
    prismaChecklistSaved: 'Checklist PRISMA-ScR sauvegardée avec succès.',
    errorSavingPrismaChecklist: 'Erreur lors de la sauvegarde de la checklist PRISMA-ScR.',
    generatingPrismaDiagram: 'Génération du diagramme PRISMA...', 
    prismaDiagramStarted: 'Génération du diagramme PRISMA lancée en arrière-plan.',
    errorGeneratingPrismaDiagram: 'Erreur lors de la génération du diagramme PRISMA',
    // Import
    selectProjectForImport: 'Veuillez sélectionner un projet pour gérer les imports et les fichiers.',
    pmidImportModalTitle: 'Import Manuel PMID/DOI',
    searchingFreePdfs: 'Recherche des PDFs gratuits...', 
    pdfSearchStarted: 'Recherche de PDFs lancée en arrière-plan.',
    generatingThesisExport: 'Génération de l\'export thèse...', 
    startingIndexing: 'Lancement de l\'indexation...', 
    indexingInProgress: 'Indexation en cours...', 
    indexingStarted: 'Indexation lancée en arrière-plan.',
    zoteroSyncNotImplemented: 'Synchronisation Zotero non implémentée dans cette version.',
    selectProject: 'Veuillez sélectionner un projet.',
    importingZotero: 'Import du fichier Zotero...', 
    referencesImported: (count) => `${count} références importées.`, 
    errorImportingZotero: 'Erreur lors de l\'import Zotero',
    pmidFieldNotFound: "Erreur : le champ d'import de PMID n'a pas été trouvé.",
    identifierRequired: 'Veuillez saisir au moins un identifiant.',
    importingIds: (count) => `Import de ${count} identifiant(s)...`, 
    importStartedForIds: (count) => `Import lancé pour ${count} identifiant(s).`, 
    errorImporting: 'Erreur lors de la sauvegarde',
    zoteroCredentialsRequired: 'L\'ID utilisateur et la clé d\'API Zotero sont requis.',
    zoteroCredentialsSaved: 'Identifiants Zotero sauvegardés avec succès.',
    errorSaving: 'Erreur lors de la sauvegarde',
    max20Pdfs: 'Maximum 20 PDFs autorisés par upload.',
    uploadingPdfs: (count) => `Upload de ${count} PDF(s)...`, 
    pdfsUploaded: (count) => `${count} PDFs uploadés`, 
    errorUploading: 'Erreur lors de l\'upload',
    // RoB
    selectProjectForRob: 'Sélectionnez un projet pour évaluer le risque de biais.',
    noArticlesInProject: 'Aucun article dans ce projet. Lancez une recherche d\'abord.',
    editButton: 'Éditer',
    runRobAnalysisButton: 'Lancer l\'analyse RoB sur la sélection',
    noRobAssessment: 'Aucune évaluation de biais pour cet article. Lancez l\'analyse.',
    errorPrefix: 'Erreur:',
    robDomainRandomization: 'Randomisation:',
    robDomainMissingData: 'Données manquantes:',
    robDomainOverall: 'Évaluation globale:',
    justificationPlaceholder: 'Justification...', 
    overallJustificationPlaceholder: 'Justification globale...', 
    cancelButton: 'Annuler',
    saveButton: 'Sauvegarder',
    savingButton: 'Sauvegarde...', 
    robAssessmentSaved: 'Évaluation RoB sauvegardée.',
    selectAtLeastOneArticleForRob: "Veuillez sélectionner au moins un article pour l\'analyse RoB.",
    startingRobAnalysis: (count) => `Lancement de l\'analyse RoB pour ${count} article(s)`, 
    robAnalysisStarted: "Analyse du risque de biais lancée. Les résultats apparaîtront progressivement.",
    // Chat
    errorLoadingChatMessages: 'Erreur lors du chargement des messages de chat:',
    noProjectSelectedChat: 'Aucun projet sélectionné',
    selectProjectForChat: 'Sélectionnez un projet pour accéder au chat RAG.',
    chatError: 'Erreur',
    errorLoadingChat: 'Erreur lors du chargement du chat.',
    chatPlaceholder: 'Posez votre question sur les PDFs indexés...', 
    sendButton: 'Envoyer',
    questionRequired: 'Veuillez saisir une question',
    questionSent: 'Question envoyée. Réponse en cours...', 
    errorSendingQuestion: 'Erreur lors de l\'envoi de la question:',
    errorSendingQuestionGeneric: 'Erreur lors de l\'envoi de la question',
    selectProjectForIndexing: 'Veuillez sélectionner un projet pour lancer l\'indexation.',
    startingPdfIndexing: 'Lancement de l\'indexation des PDFs...', 
    pdfIndexingStarted: 'Indexation des PDFs lancée en arrière-plan.',
    errorStartingIndexing: 'Erreur lors du lancement de l\'indexation',
    // Tasks
    noTasksInProgress: 'Aucune tâche en cours',
    errorLoadingTasks: 'Erreur lors du chargement des tâches:',
    // Theme
    themeToggleLabel: 'Changer le thème',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    themeLabel: 'Thème',
    themeAuto: 'Automatique',
    themeLight: 'Clair',
    themeDark: 'Sombre',
};

export const CONFIG = {
    API_BASE_URL: 'http://localhost:8080/api',
    WEBSOCKET_URL: '/',
    LOCAL_STORAGE_LAST_SECTION: 'analylit_last_section',
    COMPACT_MODE_STORAGE: 'compactMode',
};