# Dockerfile-tests
# This Dockerfile is specifically for running the test suite.

# Utilise l'image de base qui a toutes les dépendances installées
FROM analylit-base:latest

# Le WORKDIR est déjà défini dans la base, mais le répéter est une bonne pratique
WORKDIR /home/appuser/app

# La commande par défaut à exécuter au démarrage du conteneur.
# Elle exécutera la commande pytest définie dans le docker-compose.
CMD ["pytest"]