# Utilise l'image de base qui contient Python et les dépendances
FROM analylit-base:latest

# Copie uniquement le script d'attente et le script de migration
COPY . /home/appuser/app

# Donne les permissions d'exécution
USER root
RUN chmod +x /home/appuser/app/wait-for-it.sh
USER appuser