"""Add unique constraint to extractions for project_id and pmid

Revision ID: 5c739514fdf6
Revises: 9d500c0408c6
Create Date: 2025-10-08 22:37:30.292042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c739514fdf6'
down_revision = '9d500c0408c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

