"""Add unique constraint to extractions table

Revision ID: 653cfe76ecc4
Revises: 5c739514fdf6
Create Date: 2025-10-08 23:00:18.279912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653cfe76ecc4'
down_revision = '5c739514fdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
