"""Initial migration with all models

Revision ID: d3577afd6bd0
Revises: 
Create Date: 2025-09-28 18:15:11.845502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3577afd6bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('preprocess_model', sa.String(), nullable=True),
    sa.Column('extract_model', sa.String(), nullable=True),
    sa.Column('synthesis_model', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='analylit_schema'
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('profile_used', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('synthesis_result', sa.Text(), nullable=True),
    sa.Column('discussion_draft', sa.Text(), nullable=True),
    sa.Column('knowledge_graph', sa.Text(), nullable=True),
    sa.Column('prisma_flow_path', sa.String(), nullable=True),
    sa.Column('analysis_mode', sa.String(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('analysis_plot_path', sa.String(), nullable=True),
    sa.Column('pmids_count', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('databases_used', sa.Text(), nullable=True),
    sa.Column('inter_rater_reliability', sa.Text(), nullable=True),
    sa.Column('prisma_checklist', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='analylit_schema'
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('extraction_grids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_justification', sa.Text(), nullable=True),
    sa.Column('user_validation_status', sa.String(), nullable=True),
    sa.Column('analysis_source', sa.String(), nullable=True),
    sa.Column('validations', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('stakeholder_perspective', sa.String(), nullable=True),
    sa.Column('ai_type', sa.String(), nullable=True),
    sa.Column('platform_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('grey_literature',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('prisma_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('processing_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('risk_of_bias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('pmid', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('domain_1_bias', sa.String(), nullable=True),
    sa.Column('domain_1_justification', sa.Text(), nullable=True),
    sa.Column('domain_2_bias', sa.String(), nullable=True),
    sa.Column('domain_2_justification', sa.Text(), nullable=True),
    sa.Column('judgement', sa.String(), nullable=True),
    sa.Column('overall_bias', sa.String(), nullable=True),
    sa.Column('overall_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'article_id', name='uq_rob_project_article'),
    schema='analylit_schema'
    )
    op.create_table('screening_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('pmid', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'pmid', name='uq_project_pmid'),
    schema='analylit_schema'
    )
    op.create_table('search_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('database_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'article_id', name='uq_project_article'),
    schema='analylit_schema'
    )
    op.create_table('stakeholders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['analylit_schema.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('grid_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grid_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['analylit_schema.extraction_grids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    op.create_table('validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['analylit_schema.extractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analylit_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations', schema='analylit_schema')
    op.drop_table('grid_fields', schema='analylit_schema')
    op.drop_table('stakeholders', schema='analylit_schema')
    op.drop_table('search_results', schema='analylit_schema')
    op.drop_table('screening_decisions', schema='analylit_schema')
    op.drop_table('risk_of_bias', schema='analylit_schema')
    op.drop_table('processing_log', schema='analylit_schema')
    op.drop_table('prisma_records', schema='analylit_schema')
    op.drop_table('grey_literature', schema='analylit_schema')
    op.drop_table('extractions', schema='analylit_schema')
    op.drop_table('extraction_grids', schema='analylit_schema')
    op.drop_table('chat_messages', schema='analylit_schema')
    op.drop_table('articles', schema='analylit_schema')
    op.drop_table('analyses', schema='analylit_schema')
    op.drop_table('prompts', schema='analylit_schema')
    op.drop_table('projects', schema='analylit_schema')
    op.drop_table('analysis_profiles', schema='analylit_schema')
    # ### end Alembic commands ###
