"""Add unique constraint to extractions table on project_id and pmid

Revision ID: [ID_généré_par_alembic]
Revises: 653cfe76ecc4
Create Date: 2025-10-09 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32879f134ec'
down_revision = '653cfe76ecc4' # La dernière migration que vous aviez
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_extractions_project_id_pmid', # Nom de la contrainte
        'extractions',                    # Nom de la table
        ['project_id', 'pmid']            # Colonnes concernées
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_extractions_project_id_pmid', 'extractions', type_='unique')
    # ### end Alembic commands ###
